# Generated by Django 6.0.7 on 2026-07-14 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_petani', models.CharField(max_length=150)),
                ('foto_profil', models.CharField(blank=True, help_text='Simulasi URL foto profil (mis. hasil upload ke storage/CDN).', max_length=500, null=True)),
                ('tahun_pengalaman', models.PositiveIntegerField(default=0)),
                ('komoditas_utama', models.CharField(blank=True, help_text='Contoh: Padi, Jagung, Kopi', max_length=200)),
                ('deskripsi_singkat', models.TextField(blank=True, help_text='Bio singkat petani untuk ditampilkan di halaman profil.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Petani',
                'verbose_name_plural': 'Profil Petani',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lahan', models.CharField(max_length=150)),
                ('luas_lahan', models.DecimalField(decimal_places=2, help_text='Luas lahan dalam hektar (Ha).', max_digits=6)),
                ('tipe_tanah', models.CharField(max_length=100)),
                ('lokasi_daerah', models.CharField(help_text="Contoh: 'Surabaya, Jawa Timur'", max_length=150)),
                ('koordinat_dummy', models.CharField(blank=True, help_text='Teks koordinat simulasi (tidak dihitung otomatis, hanya placeholder).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm_identity', to='farm_identity.farmerprofile')),
            ],
            options={
                'verbose_name': 'Identitas Lahan',
                'verbose_name_plural': 'Identitas Lahan',
                'ordering': ['-updated_at'],
            },
        ),
    ]
