# Generated by Django 6.0.7 on 2026-07-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='foto_profil',
            field=models.ImageField(blank=True, help_text='Upload foto profil petani (opsional).', null=True, upload_to='profiles/'),
        ),
    ]
