# Generated by Django 6.0.7 on 2026-07-15 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_identity', '0002_alter_farmerprofile_foto_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(help_text='Tanggal dan waktu aktivitas dilakukan.')),
                ('aktivitas', models.CharField(help_text='Contoh: Irigasi, Pemupukan, Penanaman, Pemanenan', max_length=100)),
                ('input_digunakan', models.CharField(help_text='Bahan yang digunakan. Contoh: Air Sungai (Sekunder), Kompos Organik', max_length=200)),
                ('catatan_lapangan', models.TextField(help_text='Detail catatan aktivitas selama di lapangan.')),
                ('dokumentasi', models.ImageField(help_text='Wajib mengunggah foto bukti dokumentasi kegiatan lapangan.', upload_to='cultivation_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='farm_identity.farmidentity')),
            ],
            options={
                'verbose_name': 'Log Budidaya',
                'verbose_name_plural': 'Log Budidaya',
                'ordering': ['-tanggal'],
            },
        ),
    ]
