# Generated by Django 6.0.7 on 2026-07-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_identity', '0004_farmerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivationlog',
            name='dokumentasi',
            field=models.ImageField(help_text='Wajib mengunggah foto bukti dokumentasi kegiatan lapangan.', upload_to='dokumentasi/'),
        ),
        migrations.AlterField(
            model_name='cultivationlog',
            name='tanggal',
            field=models.DateField(help_text='Tanggal dan waktu aktivitas dilakukan.'),
        ),
    ]
