# Generated by Django 6.0.7 on 2026-07-17 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lahan', models.CharField(max_length=255)),
                ('lokasi', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanDana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('target_dana', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dana_terkumpul', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('PROSES', 'Dalam Penggalangan'), ('TERDANAI', 'Dana Terpenuhi & Berjalan'), ('PANEN', 'Sudah Panen'), ('SELESAI', 'Selesai Kontrak')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_dana', to='pendanaan.farmidentity')),
            ],
        ),
        migrations.CreateModel(
            name='InvestasiDonasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_donasi', models.CharField(choices=[('NOMINAL', 'Uang Tunai / Nominal'), ('BARANG', 'Barang / Sarana Produksi')], max_length=10)),
                ('nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('keterangan_barang', models.TextField(blank=True, null=True)),
                ('status_bagi_hasil', models.CharField(choices=[('PENDING', 'Menunggu Panen'), ('DIPROSES', 'Proses Distribusi'), ('SELESAI', 'Sudah Ditransfer')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investasi_saya', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investasi', to='pendanaan.pengajuandana')),
            ],
        ),
    ]
