# Generated by Django 6.0.7 on 2026-07-17 14:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_identity', '0005_alter_cultivationlog_dokumentasi_and_more'),
        ('pendanaan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KebutuhanBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=150)),
                ('jumlah_dibutuhkan', models.PositiveIntegerField()),
                ('satuan', models.CharField(default='item', max_length=50)),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='pengajuandana',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='investasidonasi',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='investasidonasi',
            name='pengajuan',
        ),
        migrations.CreateModel(
            name='DonasiBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.CharField(blank=True, max_length=255)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('donatur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donasi_barang', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Donasi Barang',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='DonasiBarangItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('donasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pendanaan.donasibarang')),
                ('kebutuhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_donasi', to='pendanaan.kebutuhanbarang')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True)),
                ('lokasi', models.CharField(blank=True, max_length=150)),
                ('target_dana', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='project/')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='aktif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_identity', models.ForeignKey(help_text='Identitas lahan petani pemilik proyek ini.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='farm_identity.farmidentity')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=150)),
                ('deskripsi', models.TextField(blank=True)),
                ('jumlah_pengeluaran', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bukti', models.FileField(blank=True, null=True, upload_to='laporan/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='pendanaan.project')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.AddField(
            model_name='kebutuhanbarang',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kebutuhan_barang', to='pendanaan.project'),
        ),
        migrations.CreateModel(
            name='HasilPanen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pendapatan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('keterangan', models.TextField(blank=True)),
                ('bukti', models.FileField(blank=True, null=True, upload_to='hasil_panen/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_panen', to='pendanaan.project')),
            ],
            options={
                'verbose_name_plural': 'Hasil Panen',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.AddField(
            model_name='donasibarang',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donasi_barang_set', to='pendanaan.project'),
        ),
        migrations.CreateModel(
            name='Donasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('catatan', models.CharField(blank=True, max_length=255)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('donatur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donasi_uang', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donasi_set', to='pendanaan.project')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.DeleteModel(
            name='FarmIdentity',
        ),
        migrations.DeleteModel(
            name='InvestasiDonasi',
        ),
        migrations.DeleteModel(
            name='PengajuanDana',
        ),
    ]
