# Generated by Django 6.0.7 on 2026-07-13 16:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lahan', models.CharField(help_text='Contoh: Lahan Blok A, Lahan Sektor Utara', max_length=100)),
                ('luas_lahan', models.FloatField(help_text='Luas lahan dalam satuan Hektar (Ha)')),
                ('komoditas', models.CharField(default='Padi / Beras', max_length=100)),
                ('lokasi', models.CharField(default='Semarang, Indonesia', max_length=150)),
                ('status_lahan', models.CharField(choices=[('SEHAT', 'Sehat'), ('WASPADA', 'Waspada'), ('TERSERANG', 'Terserang Hama/Penyakit')], default='SEHAT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('provincy', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LuasLahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luas_meter', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
        migrations.CreateModel(
            name='MusimTanam2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_panen', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_panen', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
                ('answ', models.TextField()),
                ('tgl', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusimTanam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_musim', models.CharField(help_text='Contoh: Mei - Agustus 2026', max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('lahan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musim_tanam_set', to='prediksi_ai_diagnosis.lahan')),
            ],
        ),
        migrations.CreateModel(
            name='PrediksiInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi_aktivitas', models.CharField(blank=True, max_length=150, null=True)),
                ('komoditas_aktivitas', models.CharField(blank=True, max_length=100, null=True)),
                ('modal', models.DecimalField(decimal_places=2, help_text='Input modal dalam Rupiah', max_digits=12)),
                ('luas_lahan', models.DecimalField(blank=True, decimal_places=2, help_text='Luas lahan yang digunakan dalam satuan meter persegi (m2)', max_digits=10, null=True)),
                ('tanggal_mulai_tanam', models.DateField(blank=True, help_text='Kapan mulai menanam', null=True)),
                ('durasi_bulan', models.IntegerField(default=5, help_text='Durasi musim tanam dalam bulan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_set', to='prediksi_ai_diagnosis.lahan')),
            ],
            options={
                'verbose_name_plural': 'Aktivitas Tanam',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='Agripreneur Level 1', max_length=50)),
                ('total_panen_musim', models.IntegerField(default=0, help_text='Total musim panen yang sudah dilalui')),
                ('ekspor_berhasil', models.IntegerField(default=0, help_text='Jumlah ekspor yang sukses')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('lokasi_asal', models.CharField(default='Semarang, Jawa Tengah', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lahan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lahan_set', to='prediksi_ai_diagnosis.profil'),
        ),
    ]
