# Generated by Django 6.0.7 on 2026-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi_ai_diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediksiinput',
            name='lahan',
            field=models.CharField(max_length=100),
        ),
    ]
