# Generated by Django 6.0.7 on 2026-07-14 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi_ai_diagnosis', '0002_alter_prediksiinput_lahan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lokasi',
        ),
        migrations.DeleteModel(
            name='LuasLahan',
        ),
        migrations.DeleteModel(
            name='MusimTanam2',
        ),
        migrations.DeleteModel(
            name='RiwayatChat',
        ),
        migrations.AddField(
            model_name='prediksiinput',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
