# Generated by Django 6.0.7 on 2026-07-16 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi_ai_diagnosis', '0003_delete_lokasi_delete_luaslahan_delete_musimtanam2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='ai_diagnosis/')),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AI Diagnoses',
                'ordering': ['-created_at'],
            },
        ),
    ]
